<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRN2SDAf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRN2SDAf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRN2SDAf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRN2SDAf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRN2SDAf\App_KernelDevDebugContainer([
    'container.build_hash' => 'RN2SDAf',
    'container.build_id' => '89b9d4b8',
    'container.build_time' => 1727628500,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRN2SDAf');
