<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJtTfF1f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJtTfF1f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJtTfF1f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJtTfF1f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJtTfF1f\App_KernelDevDebugContainer([
    'container.build_hash' => 'JtTfF1f',
    'container.build_id' => '914a32bf',
    'container.build_time' => 1727621879,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJtTfF1f');
