<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBdxN7Ba\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBdxN7Ba/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBdxN7Ba.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBdxN7Ba\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBdxN7Ba\App_KernelDevDebugContainer([
    'container.build_hash' => 'BdxN7Ba',
    'container.build_id' => 'ee1190a8',
    'container.build_time' => 1727627438,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBdxN7Ba');
