<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Invoice extends \App\Entity\Invoice implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null],
        "\0".parent::class."\0".'callbacks' => [parent::class, 'callbacks', null],
        "\0".parent::class."\0".'currency' => [parent::class, 'currency', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'qrCode' => [parent::class, 'qrCode', null],
        "\0".parent::class."\0".'requestData' => [parent::class, 'requestData', null],
        "\0".parent::class."\0".'responseData' => [parent::class, 'responseData', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        'amount' => [parent::class, 'amount', null],
        'callbacks' => [parent::class, 'callbacks', null],
        'currency' => [parent::class, 'currency', null],
        'id' => [parent::class, 'id', null],
        'qrCode' => [parent::class, 'qrCode', null],
        'requestData' => [parent::class, 'requestData', null],
        'responseData' => [parent::class, 'responseData', null],
        'status' => [parent::class, 'status', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
