<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UKj8i7yService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.uKj8i7y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uKj8i7y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'DTO' => ['privates', 'App\\DTO\\CallbackDTO', 'getCallbackDTOService', true],
            'action' => ['privates', 'App\\Service\\Payment\\Callback\\CallbackAction', 'getCallbackActionService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'DTO' => 'App\\DTO\\CallbackDTO',
            'action' => 'App\\Service\\Payment\\Callback\\CallbackAction',
            'validator' => '?',
        ]);
    }
}
