<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallbackActionService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Payment\Callback\CallbackAction' shared autowired service.
     *
     * @return \App\Service\Payment\Callback\CallbackAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/Callback/CallbackAction.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Payment\\Callback\\CallbackAction'])) {
            return $container->privates['App\\Service\\Payment\\Callback\\CallbackAction'];
        }
        $b = ($container->privates['serializer'] ?? self::getSerializerService($container));

        if (isset($container->privates['App\\Service\\Payment\\Callback\\CallbackAction'])) {
            return $container->privates['App\\Service\\Payment\\Callback\\CallbackAction'];
        }

        return $container->privates['App\\Service\\Payment\\Callback\\CallbackAction'] = new \App\Service\Payment\Callback\CallbackAction(($container->privates['App\\Repository\\InvoiceRepository'] ?? $container->load('getInvoiceRepositoryService')), $a, $b);
    }
}
