<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Form_Date_JavascriptFormatConverterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.form.date.javascript_format_converter' shared service.
     *
     * @return \Sonata\Form\Date\JavaScriptFormatConverter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Date/JavaScriptFormatConverter.php';

        return $container->privates['sonata.form.date.javascript_format_converter'] = new \Sonata\Form\Date\JavaScriptFormatConverter();
    }
}
