<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Action_SetObjectFieldValueService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sonata.admin.action.set_object_field_value' shared service.
     *
     * @return \Sonata\AdminBundle\Action\SetObjectFieldValueAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Action/SetObjectFieldValueAction.php';

        return $container->services['sonata.admin.action.set_object_field_value'] = new \Sonata\AdminBundle\Action\SetObjectFieldValueAction(($container->privates['twig'] ?? self::getTwigService($container)), ($container->privates['sonata.admin.request.fetcher'] ?? $container->load('getSonata_Admin_Request_FetcherService')), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)), ($container->privates['sonata.admin.form.data_transformer_resolver'] ?? $container->load('getSonata_Admin_Form_DataTransformerResolverService')), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), ($container->privates['sonata.admin.twig.render_element_runtime'] ?? self::getSonata_Admin_Twig_RenderElementRuntimeService($container)));
    }
}
