<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSuccessResponseResponseMockService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Payment\Invoice\Mock\Response\SuccessResponseResponseMock' shared autowired service.
     *
     * @return \App\Service\Payment\Invoice\Mock\Response\SuccessResponseResponseMock
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/ResponseInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/Invoice/Mock/MockInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/Invoice/Mock/AbstractCreateInvoiceResponseMock.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/Invoice/Mock/Response/SuccessResponseResponseMock.php';

        return $container->privates['App\\Service\\Payment\\Invoice\\Mock\\Response\\SuccessResponseResponseMock'] = new \App\Service\Payment\Invoice\Mock\Response\SuccessResponseResponseMock();
    }
}
