<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Exporter_Writer_XlsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.exporter.writer.xls' shared service.
     *
     * @return \Sonata\Exporter\Writer\XlsWriter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/TypedWriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/XlsWriter.php';

        return $container->privates['sonata.exporter.writer.xls'] = new \Sonata\Exporter\Writer\XlsWriter('php://output', true);
    }
}
