<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Exporter_Writer_XmlService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.exporter.writer.xml' shared service.
     *
     * @return \Sonata\Exporter\Writer\XmlWriter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/TypedWriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/XmlWriter.php';

        return $container->privates['sonata.exporter.writer.xml'] = new \Sonata\Exporter\Writer\XmlWriter('php://output', 'datas', 'data');
    }
}
