<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Search_HandlerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.search.handler' shared service.
     *
     * @return \Sonata\AdminBundle\Search\SearchHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Search/SearchHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Search/SearchHandler.php';

        $container->privates['sonata.admin.search.handler'] = $instance = new \Sonata\AdminBundle\Search\SearchHandler();

        $instance->configureAdminSearch([]);

        return $instance;
    }
}
