<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Form_DataTransformerResolverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.form.data_transformer_resolver' shared service.
     *
     * @return \Sonata\AdminBundle\Form\DataTransformerResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Form/DataTransformerResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Form/DataTransformerResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Form/DataTransformer/BooleanToStringTransformer.php';

        $container->privates['sonata.admin.form.data_transformer_resolver'] = $instance = new \Sonata\AdminBundle\Form\DataTransformerResolver();

        $instance->addCustomGlobalTransformer('boolean', ($container->privates['sonata.admin.form.data_transformer.boolean_to_string'] ??= new \Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer(1)));

        return $instance;
    }
}
