<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Twig_StatusRuntimeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.twig.status_runtime' shared service.
     *
     * @return \Sonata\Twig\Extension\StatusRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/twig-extensions/src/Extension/StatusRuntime.php';

        return $container->privates['sonata.twig.status_runtime'] = new \Sonata\Twig\Extension\StatusRuntime();
    }
}
