<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Doctrine_Adapter_DoctrineOrmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.doctrine.adapter.doctrine_orm' shared service.
     *
     * @return \Sonata\Doctrine\Adapter\ORM\DoctrineORMAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/ORM/DoctrineORMAdapter.php';

        return $container->privates['sonata.doctrine.adapter.doctrine_orm'] = new \Sonata\Doctrine\Adapter\ORM\DoctrineORMAdapter(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
