<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Builder_OrmDatagridService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.builder.orm_datagrid' shared service.
     *
     * @return \Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Builder/BuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Builder/DatagridBuilderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-orm-admin-bundle/src/Builder/DatagridBuilder.php';

        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->privates['sonata.admin.builder.orm_datagrid'])) {
            return $container->privates['sonata.admin.builder.orm_datagrid'];
        }

        return $container->privates['sonata.admin.builder.orm_datagrid'] = new \Sonata\DoctrineORMAdminBundle\Builder\DatagridBuilder($a, ($container->privates['sonata.admin.builder.filter.factory'] ?? $container->load('getSonata_Admin_Builder_Filter_FactoryService')), ($container->privates['sonata.admin.guesser.orm_datagrid_chain'] ?? $container->load('getSonata_Admin_Guesser_OrmDatagridChainService')), true);
    }
}
