<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignatureServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Payment\SignatureService' shared autowired service.
     *
     * @return \App\Service\Payment\SignatureService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/SignatureService.php';

        return $container->privates['App\\Service\\Payment\\SignatureService'] = new \App\Service\Payment\SignatureService(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)));
    }
}
