<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Form_DataTransformer_BooleanToStringService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.form.data_transformer.boolean_to_string' shared service.
     *
     * @return \Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/DataTransformerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Form/DataTransformer/BooleanToStringTransformer.php';

        return $container->privates['sonata.admin.form.data_transformer.boolean_to_string'] = new \Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer(1);
    }
}
