<?php

namespace Container7yp5AW9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_ArgumentResolver_AdminService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.argument_resolver.admin' shared service.
     *
     * @return \Sonata\AdminBundle\ArgumentResolver\AdminValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/ArgumentResolver/CompatibleValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/ArgumentResolver/AdminValueResolver.php';

        $a = ($container->privates['sonata.admin.request.fetcher'] ?? $container->load('getSonata_Admin_Request_FetcherService'));

        if (isset($container->privates['sonata.admin.argument_resolver.admin'])) {
            return $container->privates['sonata.admin.argument_resolver.admin'];
        }

        return $container->privates['sonata.admin.argument_resolver.admin'] = new \Sonata\AdminBundle\ArgumentResolver\AdminValueResolver($a);
    }
}
