<?php

namespace ContainerLUjYrrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ImiNvZ_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.imiNvZ.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.imiNvZ.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CallbackController::handleCallback' => ['privates', '.service_locator.uKj8i7y', 'get_ServiceLocator_UKj8i7yService', true],
            'App\\Controller\\InvoiceController::getInvoiceSignature' => ['privates', '.service_locator.yNJ0lDi', 'get_ServiceLocator_YNJ0lDiService', true],
            'App\\Controller\\InvoiceController::handleInvoice' => ['privates', '.service_locator.QGMB0r.', 'get_ServiceLocator_QGMB0r_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CallbackController:handleCallback' => ['privates', '.service_locator.uKj8i7y', 'get_ServiceLocator_UKj8i7yService', true],
            'App\\Controller\\InvoiceController:getInvoiceSignature' => ['privates', '.service_locator.yNJ0lDi', 'get_ServiceLocator_YNJ0lDiService', true],
            'App\\Controller\\InvoiceController:handleInvoice' => ['privates', '.service_locator.QGMB0r.', 'get_ServiceLocator_QGMB0r_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CallbackController::handleCallback' => '?',
            'App\\Controller\\InvoiceController::getInvoiceSignature' => '?',
            'App\\Controller\\InvoiceController::handleInvoice' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CallbackController:handleCallback' => '?',
            'App\\Controller\\InvoiceController:getInvoiceSignature' => '?',
            'App\\Controller\\InvoiceController:handleInvoice' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
