<?php

namespace ContainerLUjYrrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallbackControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\CallbackController' shared autowired service.
     *
     * @return \App\Controller\CallbackController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CallbackController.php';

        $container->services['App\\Controller\\CallbackController'] = $instance = new \App\Controller\CallbackController(($container->privates['App\\Service\\Payment\\SignatureService'] ?? $container->load('getSignatureServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\CallbackController', $container));

        return $instance;
    }
}
