<?php

namespace ContainerLUjYrrI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaker_AutoCommand_MakeSonataAdminService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'maker.auto_command.make_sonata_admin' shared service.
     *
     * @return \Symfony\Bundle\MakerBundle\Command\MakerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Command/MakerCommand.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/MakerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Maker/AbstractMaker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Maker/AdminMaker.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Model/ModelManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Model/LockInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Model/ProxyResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-orm-admin-bundle/src/Model/ModelManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/maker-bundle/src/Util/TemplateLinter.php';

        $container->privates['maker.auto_command.make_sonata_admin'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Sonata\AdminBundle\Maker\AdminMaker(\dirname(__DIR__, 4), ['sonata.admin.manager.orm' => new \Sonata\DoctrineORMAdminBundle\Model\ModelManager(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)))], 'Sonata\\AdminBundle\\Controller\\CRUDController'), ($container->privates['maker.file_manager'] ?? $container->load('getMaker_FileManagerService')), ($container->privates['maker.generator'] ?? $container->load('getMaker_GeneratorService')), ($container->privates['maker.template_linter'] ??= new \Symfony\Bundle\MakerBundle\Util\TemplateLinter($container->getEnv('default::string:MAKER_PHP_CS_FIXER_BINARY_PATH'), $container->getEnv('default::string:MAKER_PHP_CS_FIXER_CONFIG_PATH'))));

        $instance->setName('make:sonata:admin');
        $instance->setDescription('Generates an admin class based on the given model class');

        return $instance;
    }
}
