<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceFactoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\Payment\Invoice\InvoiceFactory' shared autowired service.
     *
     * @return \App\Service\Payment\Invoice\InvoiceFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Payment/Invoice/InvoiceFactory.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Payment\\Invoice\\InvoiceFactory'])) {
            return $container->privates['App\\Service\\Payment\\Invoice\\InvoiceFactory'];
        }

        return $container->privates['App\\Service\\Payment\\Invoice\\InvoiceFactory'] = new \App\Service\Payment\Invoice\InvoiceFactory($a);
    }
}
