<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\InvoiceController' shared autowired service.
     *
     * @return \App\Controller\InvoiceController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InvoiceController.php';

        $container->services['App\\Controller\\InvoiceController'] = $instance = new \App\Controller\InvoiceController(($container->privates['App\\Service\\Payment\\SignatureService'] ?? $container->load('getSignatureServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InvoiceController', $container));

        return $instance;
    }
}
