<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInvoiceDTOService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\DTO\InvoiceDTO' shared autowired service.
     *
     * @return \App\DTO\InvoiceDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DTO/InvoiceDTO.php';

        return $container->privates['App\\DTO\\InvoiceDTO'] = new \App\DTO\InvoiceDTO();
    }
}
