<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Block_SearchResultService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sonata.admin.block.search_result' shared service.
     *
     * @return \Sonata\AdminBundle\Block\AdminSearchBlockService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/BlockServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Block/AdminSearchBlockService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['sonata.admin.block.search_result'])) {
            return $container->services['sonata.admin.block.search_result'];
        }
        $b = ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container));

        if (isset($container->services['sonata.admin.block.search_result'])) {
            return $container->services['sonata.admin.block.search_result'];
        }

        return $container->services['sonata.admin.block.search_result'] = new \Sonata\AdminBundle\Block\AdminSearchBlockService($a, $b, ($container->privates['sonata.admin.search.handler'] ?? $container->load('getSonata_Admin_Search_HandlerService')), ($container->privates['sonata.admin.global_template_registry'] ?? self::getSonata_Admin_GlobalTemplateRegistryService($container)), 'show', 'show');
    }
}
