<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Exporter_ExporterService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sonata.exporter.exporter' shared service.
     *
     * @return \Sonata\Exporter\Exporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/ExporterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Exporter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/TypedWriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/JsonWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/XlsWriter.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/XmlWriter.php';

        $container->services['sonata.exporter.exporter'] = $instance = new \Sonata\Exporter\Exporter();

        $instance->addWriter(($container->privates['sonata.exporter.writer.csv'] ?? $container->load('getSonata_Exporter_Writer_CsvService')));
        $instance->addWriter(($container->privates['sonata.exporter.writer.json'] ??= new \Sonata\Exporter\Writer\JsonWriter('php://output')));
        $instance->addWriter(($container->privates['sonata.exporter.writer.xls'] ??= new \Sonata\Exporter\Writer\XlsWriter('php://output', true)));
        $instance->addWriter(($container->privates['sonata.exporter.writer.xml'] ??= new \Sonata\Exporter\Writer\XmlWriter('php://output', 'datas', 'data')));

        return $instance;
    }
}
