<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Doctrine_Model_Adapter_ChainService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'sonata.doctrine.model.adapter.chain' shared service.
     *
     * @return \Sonata\Doctrine\Adapter\AdapterChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/AdapterChain.php';

        $container->services['sonata.doctrine.model.adapter.chain'] = $instance = new \Sonata\Doctrine\Adapter\AdapterChain();

        $instance->addAdapter(($container->privates['sonata.doctrine.adapter.doctrine_orm'] ?? $container->load('getSonata_Doctrine_Adapter_DoctrineOrmService')));

        return $instance;
    }
}
