<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Menu_GroupProviderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.menu.group_provider' shared service.
     *
     * @return \Sonata\AdminBundle\Menu\Provider\GroupMenuProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Menu/Provider/GroupMenuProvider.php';

        $a = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }
        $b = ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container));

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }
        $c = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['sonata.admin.menu.group_provider'])) {
            return $container->privates['sonata.admin.menu.group_provider'];
        }

        return $container->privates['sonata.admin.menu.group_provider'] = new \Sonata\AdminBundle\Menu\Provider\GroupMenuProvider($a, $b, $c);
    }
}
