<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_MenuBuilderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.menu_builder' shared service.
     *
     * @return \Sonata\AdminBundle\Menu\MenuBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Menu/MenuBuilder.php';

        $a = ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $b = ($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService'));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $c = ($container->privates['knp_menu.menu_provider.chain'] ?? self::getKnpMenu_MenuProvider_ChainService($container));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }
        $d = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['sonata.admin.menu_builder'])) {
            return $container->privates['sonata.admin.menu_builder'];
        }

        return $container->privates['sonata.admin.menu_builder'] = new \Sonata\AdminBundle\Menu\MenuBuilder($a, $b, $c, $d);
    }
}
