<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_TranslationExtractorService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.translation_extractor' shared service.
     *
     * @return \Sonata\AdminBundle\Translator\Extractor\AdminExtractor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/translation/Extractor/ExtractorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Translator/LabelTranslatorStrategyInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Translator/Extractor/AdminExtractor.php';

        return $container->privates['sonata.admin.translation_extractor'] = new \Sonata\AdminBundle\Translator\Extractor\AdminExtractor(($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container)), ($container->privates['sonata.admin.breadcrumbs_builder'] ?? self::getSonata_Admin_BreadcrumbsBuilderService($container)));
    }
}
