<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Guesser_OrmShowChainService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.guesser.orm_show_chain' shared service.
     *
     * @return \Sonata\AdminBundle\FieldDescription\TypeGuesserChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/FieldDescription/TypeGuesserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/FieldDescription/TypeGuesserChain.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-orm-admin-bundle/src/FieldDescription/TypeGuesser.php';

        return $container->privates['sonata.admin.guesser.orm_show_chain'] = new \Sonata\AdminBundle\FieldDescription\TypeGuesserChain([($container->privates['sonata.admin.guesser.orm_show'] ??= new \Sonata\DoctrineORMAdminBundle\FieldDescription\TypeGuesser())]);
    }
}
