<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Exporter_Writer_CsvService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.exporter.writer.csv' shared service.
     *
     * @return \Sonata\Exporter\Writer\CsvWriter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/WriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/TypedWriterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/exporter/src/Writer/CsvWriter.php';

        return $container->privates['sonata.exporter.writer.csv'] = new \Sonata\Exporter\Writer\CsvWriter('php://output', ',', '"', '\\', true, false);
    }
}
