<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Form_Type_DatetimePickerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.form.type.datetime_picker' shared service.
     *
     * @return \Sonata\Form\Type\DateTimePickerType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Type/BasePickerType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Type/DateTimePickerType.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/form-extensions/src/Date/JavaScriptFormatConverter.php';

        return $container->privates['sonata.form.type.datetime_picker'] = new \Sonata\Form\Type\DateTimePickerType(($container->privates['sonata.form.date.javascript_format_converter'] ??= new \Sonata\Form\Date\JavaScriptFormatConverter()), 'en');
    }
}
