<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_ArgumentResolver_ProxyQueryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.argument_resolver.proxy_query' shared service.
     *
     * @return \Sonata\AdminBundle\ArgumentResolver\ProxyQueryResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/Controller/ValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/ArgumentResolver/CompatibleValueResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/ArgumentResolver/ProxyQueryResolver.php';

        return $container->privates['sonata.admin.argument_resolver.proxy_query'] = new \Sonata\AdminBundle\ArgumentResolver\ProxyQueryResolver();
    }
}
