<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Block_Service_MenuService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.block.service.menu' shared service.
     *
     * @return \Sonata\BlockBundle\Block\Service\MenuBlockService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/BlockServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/EditableBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractMenuBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/MenuBlockService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->privates['sonata.block.service.menu'])) {
            return $container->privates['sonata.block.service.menu'];
        }
        $b = ($container->privates['knp_menu.menu_provider.chain'] ?? self::getKnpMenu_MenuProvider_ChainService($container));

        if (isset($container->privates['sonata.block.service.menu'])) {
            return $container->privates['sonata.block.service.menu'];
        }

        return $container->privates['sonata.block.service.menu'] = new \Sonata\BlockBundle\Block\Service\MenuBlockService($a, $b, ($container->services['sonata.block.menu.registry'] ?? $container->load('getSonata_Block_Menu_RegistryService')));
    }
}
