<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_RouteLoaderService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.route_loader' shared service.
     *
     * @return \Sonata\AdminBundle\Route\AdminPoolLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/config/Loader/Loader.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Route/AdminPoolLoader.php';

        $a = ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container));

        if (isset($container->privates['sonata.admin.route_loader'])) {
            return $container->privates['sonata.admin.route_loader'];
        }

        return $container->privates['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader($a);
    }
}
