<?php

namespace ContainerMIBOmSB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_DataSource_OrmService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'sonata.admin.data_source.orm' shared service.
     *
     * @return \Sonata\DoctrineORMAdminBundle\Exporter\DataSource
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Exporter/DataSourceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-orm-admin-bundle/src/Exporter/DataSource.php';

        return $container->privates['sonata.admin.data_source.orm'] = new \Sonata\DoctrineORMAdminBundle\Exporter\DataSource();
    }
}
