<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6hdlyxy\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6hdlyxy/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container6hdlyxy.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container6hdlyxy\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container6hdlyxy\App_KernelTestDebugContainer([
    'container.build_hash' => '6hdlyxy',
    'container.build_id' => '94b1b2a6',
    'container.build_time' => 1727628340,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6hdlyxy');
