<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerChMmHsz\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerChMmHsz/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerChMmHsz.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerChMmHsz\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerChMmHsz\App_KernelTestDebugContainer([
    'container.build_hash' => 'ChMmHsz',
    'container.build_id' => 'a5ec4013',
    'container.build_time' => 1727630068,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerChMmHsz');
