<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMIBOmSB\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMIBOmSB/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerMIBOmSB.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerMIBOmSB\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerMIBOmSB\App_KernelTestDebugContainer([
    'container.build_hash' => 'MIBOmSB',
    'container.build_id' => 'a4cb9734',
    'container.build_time' => 1727573011,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMIBOmSB');
