<?php

namespace ContainerJtTfF1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QGMB0r_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QGMB0r.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QGMB0r.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'DTO' => ['privates', 'App\\DTO\\InvoiceDTO', 'getInvoiceDTOService', true],
            'action' => ['privates', 'App\\Service\\Payment\\Invoice\\CreateInvoiceAction', 'getCreateInvoiceActionService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'invoiceFactory' => ['privates', 'App\\Service\\Payment\\Invoice\\InvoiceFactory', 'getInvoiceFactoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'DTO' => 'App\\DTO\\InvoiceDTO',
            'action' => 'App\\Service\\Payment\\Invoice\\CreateInvoiceAction',
            'entityManager' => '?',
            'invoiceFactory' => 'App\\Service\\Payment\\Invoice\\InvoiceFactory',
            'validator' => '?',
        ]);
    }
}
