<?php

namespace ContainerJtTfF1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCallbackDTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\DTO\CallbackDTO' shared autowired service.
     *
     * @return \App\DTO\CallbackDTO
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/DTO/CallbackDTO.php';

        return $container->privates['App\\DTO\\CallbackDTO'] = new \App\DTO\CallbackDTO();
    }
}
