<?php

namespace ContainerJtTfF1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Doctrine_Model_Adapter_ChainService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.doctrine.model.adapter.chain' shared service.
     *
     * @return \Sonata\Doctrine\Adapter\AdapterChain
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/AdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/AdapterChain.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/doctrine-extensions/src/Adapter/ORM/DoctrineORMAdapter.php';

        $container->services['sonata.doctrine.model.adapter.chain'] = $instance = new \Sonata\Doctrine\Adapter\AdapterChain();

        $instance->addAdapter(new \Sonata\Doctrine\Adapter\ORM\DoctrineORMAdapter(($container->services['doctrine'] ?? self::getDoctrineService($container))));

        return $instance;
    }
}
