<?php

namespace ContainerJtTfF1f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSonata_Admin_Block_AdminListService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'sonata.admin.block.admin_list' shared service.
     *
     * @return \Sonata\AdminBundle\Block\AdminListBlockService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/BlockServiceInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/block-bundle/src/Block/Service/AbstractBlockService.php';
        include_once \dirname(__DIR__, 4).'/vendor/sonata-project/admin-bundle/src/Block/AdminListBlockService.php';

        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['sonata.admin.block.admin_list'])) {
            return $container->services['sonata.admin.block.admin_list'];
        }
        $b = ($container->privates['sonata.admin.pool'] ?? self::getSonata_Admin_PoolService($container));

        if (isset($container->services['sonata.admin.block.admin_list'])) {
            return $container->services['sonata.admin.block.admin_list'];
        }

        return $container->services['sonata.admin.block.admin_list'] = new \Sonata\AdminBundle\Block\AdminListBlockService($a, $b, ($container->privates['sonata.admin.global_template_registry'] ?? self::getSonata_Admin_GlobalTemplateRegistryService($container)));
    }
}
